<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://cps.huawei.com/cpsinterface/request" xmlns:req="http://cps.huawei.com/cpsinterface/request" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://cps.huawei.com/cpsinterface/request" xmlns:wsa="http://www.w3.org/2005/08/addressing/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="CBPInterface_Request_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="RequestBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    
          <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://cps.huawei.com/cpsinterface/request" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="CBPInterface_Request_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="RequestMessage">
    <wsdl:part element="req:RequestMsg" name="RequestMsg"/>
  </wsdl:message>
  <wsdl:message name="ResponseMessage">
    <wsdl:part element="req:ResponseMsg" name="ResponseMsg"/>
  </wsdl:message>
  <wsdl:portType name="RequestMgrPortType">
    <wsdl:operation name="GenericAPIRequest">
      <wsdl:input message="req:RequestMessage"/>
      <wsdl:output message="req:ResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RequestBinding" type="req:RequestMgrPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GenericAPIRequest">
      <soap:operation soapAction="GenericAPIRequest" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RequestMgrService">
    <wsdl:port binding="req:RequestBinding" name="RequestMgrServicePort">
      <soap:address location="http://cps.huawei.com/cpsinterface/request"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>